name: Version

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Please select the type to publish
        required: true
        type: choice
        options:
          - alpha
          - beta
          - latest
        default: 'latest'

jobs:
  update_version:
    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          yarn
          yarn bootstrap

      - name: Update Version
        run: yarn run v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Generate version and changelog
          title: Update Version
          body: Update the version and changelog of the package
          branch: release/${{ steps.date.outputs.today }}
          base: main
