name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged == true
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo $HOME/ ${{ github.ref }} ${{ github.head_ref }} ${{ github.event.pull_request.merged }}

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Creating .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Setup Node.js 14.17.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.x

      - name: Install dependencies
        run: |
          yarn
          yarn bootstrap

      - name: Build packages
        run: |
          yarn run build

      - name: Publish
        run: yarn run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push Tags
        run: |
          git push --follow-tags
